/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-12-08 06:00:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productManegement2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/qkrwo/Desktop/sist_ShoppingMall/shop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/qkrwo/Desktop/sist_ShoppingMall/shop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605232503631L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link href=\"/web/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"/web/css/kfonts2.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"css/maincss.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(function() {\n");
      out.write("\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div class=\"wrap\">\n");
      out.write("\t\t<div class=\"mainWrap\">\n");
      out.write("\t\t\t<div class=\"mainContents\">\n");
      out.write("\t\t\t\t<h1 align=\"center\">재고관리</h1>\n");
      out.write("\t\t\t\t<br> <br>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<form role=\"form\" class=\"form-inline text-center\">\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\" id=\"year\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">2020</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2019</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">2018</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">2017</option>\n");
      out.write("\t\t\t\t\t\t</select> <select class=\"form-control \" id=\"month\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">01</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">02</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">03</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">04</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">05</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"6\">06</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"7\">07</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"8\">08</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"9\">09</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\">10</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"11\">11</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"12\">12</option>\n");
      out.write("\t\t\t\t\t\t</select> <select class=\"form-control id=\"day\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">01</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">02</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">03</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">04</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">05</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"6\">06</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"7\">07</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"8\">08</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"9\">09</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\">10</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"11\">11</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"12\">12</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"13\">13</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"14\">14</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"15\">15</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"16\">16</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"17\">17</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"18\">18</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"19\">19</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20\">20</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"21\">21</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"22\">22</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"23\">23</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"24\">24</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"25\">25</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"26\">26</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"27\">27</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"28\">28</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"29\">29</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"30\">30</option>\n");
      out.write("\t\t\t\t\t\t</select> \n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">전체</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">상품번호</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">상품명</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">상품분류</option>\n");
      out.write("\t\t\t\t\t\t</select> \n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control input-s\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-s\">검색</button>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t<br><br>\n");
      out.write("\n");
      out.write("\t\t\t\t<form role=\"form\" class=\"form-inline pull-right\">\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-s glyphicon glyphicon-remove\">삭제</button>\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-s glyphicon glyphicon-floppy-disk\">저장</button>\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-hover table-bordered\">\n");
      out.write("\t\t\t\t\t\t\t<thead style=\"background-color: #eeeeee\">\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\"><input type=\"checkbox\"></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">No</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">상품번호</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">분류</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">상품명</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">수량</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">가격</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">사진</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">상품설명</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th class=\"text-center\">출시일</th>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-center\"><input type=\"checkbox\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-center\">1</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-center\">201119</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-center\">상의</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-center\">후드티</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-center\">5</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-right\">50,000원</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-center\">없음</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-left\">기본 후드티</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-center\">2020-11-19</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"text-center\">\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-chevron-left\"></span>\n");
      out.write("\t\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">1</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">2</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">3</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">4</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">5</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-chevron-right\"></span>\n");
      out.write("\t\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div>\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"/web/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
