/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-12-03 08:00:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SignIn2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>NO NAME LOGIN</title>\n");
      out.write("<link href=\"css/maincss.css\" rel=\"stylesheet\">\n");
      out.write("<style rel=\"stylesheet\">\n");
      out.write("@import url(https://fonts.googleapis.com/css?family=Lato:400,700);\n");
      out.write("\n");
      out.write("* {\n");
      out.write("\tbox-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn {\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("\tbackground-color: #f8f8f8;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container {\n");
      out.write("\tposition: relative;\n");
      out.write("\toverflow: hidden;\n");
      out.write("\twidth: 400px;\n");
      out.write("\theight: 550px;\n");
      out.write("\tmargin: 80px auto 0;\n");
      out.write("\tbackground-color: #ffffff;\n");
      out.write("\tbox-shadow: rgba(0, 0, 0, 0.1) 0px 10px 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .half {\n");
      out.write("\tfloat: left;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 100%;\n");
      out.write("\tpadding: 58px 40px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container h1 {\n");
      out.write("\tfont-size: 18px;\n");
      out.write("\tfont-weight: 700;\n");
      out.write("\tmargin-bottom: 23px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\ttext-indent: 6px;\n");
      out.write("\tletter-spacing: 7px;\n");
      out.write("\ttext-transform: uppercase;\n");
      out.write("\tcolor: #263238;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .tabs {\n");
      out.write("\twidth: 100%;\n");
      out.write("\tmargin-bottom: 29px;\n");
      out.write("\tborder-bottom: 1px solid #d9d9d9;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .tabs .tab {\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\tmargin-bottom: -1px;\n");
      out.write("\tpadding: 20px 15px 10px;\n");
      out.write("\tcursor: pointer;\n");
      out.write("\tletter-spacing: 0;\n");
      out.write("\tborder-bottom: 1px solid #d9d9d9;\n");
      out.write("\tuser-select: none;\n");
      out.write("\ttransition: all 0.1s ease-in-out;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .tabs .tab a {\n");
      out.write("\tfont-size: 11px;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\ttext-transform: uppercase;\n");
      out.write("\tcolor: #d9d9d9;\n");
      out.write("\ttransition: all 0.1s ease-in-out;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .tabs .tab.active a, #signIn .container .tabs .tab:hover a\n");
      out.write("\t{\n");
      out.write("\tcolor: #263238;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .tabs .tab.active {\n");
      out.write("\tborder-bottom: 1px solid #263238;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content form {\n");
      out.write("\tposition: relative;\n");
      out.write("\theight: 320px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content label {\n");
      out.write("\tfont-size: 12px;\n");
      out.write("\tcolor: #263238;\n");
      out.write("\t-moz-user-select: -moz-none;\n");
      out.write("\t-ms-user-select: none;\n");
      out.write("\t-webkit-user-select: none;\n");
      out.write("\tuser-select: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content input.inpt {\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\tdisplay: block;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 42px;\n");
      out.write("\tmargin-bottom: 12px;\n");
      out.write("\tpadding: 16px 13px;\n");
      out.write("\tcolor: #999999;\n");
      out.write("\tborder: 1px solid #d9d9d9;\n");
      out.write("\tbackground: transparent;\n");
      out.write("\t-moz-border-radius: 2px;\n");
      out.write("\t-webkit-border-radius: 2px;\n");
      out.write("\tborder-radius: 2px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content input.inpt::-webkit-input-placeholder\n");
      out.write("\t{\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\tcolor: #999999;\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content input.inpt:focus {\n");
      out.write("\tborder-color: #999999;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content input.submit {\n");
      out.write("\tfont-size: 12px;\n");
      out.write("\tline-height: 42px;\n");
      out.write("\tdisplay: block;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 42px;\n");
      out.write("\tcursor: pointer;\n");
      out.write("\tvertical-align: middle;\n");
      out.write("\tletter-spacing: 2px;\n");
      out.write("\ttext-transform: uppercase;\n");
      out.write("\tcolor: #263238;\n");
      out.write("\tborder: 1px solid #263238;\n");
      out.write("\tbackground: transparent;\n");
      out.write("\t-moz-border-radius: 2px;\n");
      out.write("\t-webkit-border-radius: 2px;\n");
      out.write("\tborder-radius: 2px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content input.submit:hover {\n");
      out.write("\tbackground-color: #263238;\n");
      out.write("\tcolor: #ffffff;\n");
      out.write("\t-moz-transition: all 0.2s;\n");
      out.write("\t-o-transition: all 0.2s;\n");
      out.write("\t-webkit-transition: all 0.2s;\n");
      out.write("\ttransition: all 0.2s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content input:focus {\n");
      out.write("\toutline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content .checkbox {\n");
      out.write("\tmargin-top: 4px;\n");
      out.write("\toverflow: hidden;\n");
      out.write("\tclip: rect(0, 0, 0, 0);\n");
      out.write("\twidth: 0;\n");
      out.write("\theight: 0;\n");
      out.write("\tmargin: 17px -1px;\n");
      out.write("\tpadding: 0;\n");
      out.write("\tborder: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content .checkbox+label {\n");
      out.write("\tvertical-align: middle;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\twidth: 50%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content .checkbox+label:before {\n");
      out.write("\tcontent: \"\\A\";\n");
      out.write("\tcolor: #999999;\n");
      out.write("\tfont-family: Verdana;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\tfont-size: 8px;\n");
      out.write("\tline-height: 10px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\tvertical-align: middle;\n");
      out.write("\tposition: relative;\n");
      out.write("\t-moz-border-radius: 2px;\n");
      out.write("\t-webkit-border-radius: 2px;\n");
      out.write("\tborder-radius: 2px;\n");
      out.write("\tbackground: transparent;\n");
      out.write("\tborder: 1px solid #d9d9d9;\n");
      out.write("\twidth: 11px;\n");
      out.write("\theight: 11px;\n");
      out.write("\tmargin: -2px 8px 0 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content .submit-wrap {\n");
      out.write("\tposition: absolute;\n");
      out.write("\tbottom: 0;\n");
      out.write("\twidth: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content .submit-wrap a {\n");
      out.write("\tfont-size: 12px;\n");
      out.write("\tdisplay: block;\n");
      out.write("\tmargin-top: 20px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcolor: #999999;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content .submit-wrap a:hover {\n");
      out.write("\ttext-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#signIn .mainWrap .container .content .signup-cont {\n");
      out.write("\tdisplay: none;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("<body id=\"signIn\">\n");
      out.write("\t<div class=\"wrap\">\n");
      out.write("\t\t<div class=\"mainWrap\">\n");
      out.write("\t\t\t<section class=\"container\">\n");
      out.write("\t\t\t\t<article class=\"half\">\n");
      out.write("\t\t\t\t\t<h1>NONAME</h1>\n");
      out.write("\t\t\t\t\t<div class=\"tabs\">\n");
      out.write("\t\t\t\t\t\t<span class=\"tab signin active\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#signin\">Sign in</a>\n");
      out.write("\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"content\">\n");
      out.write("\t\t\t\t\t\t<div class=\"signin-cont cont\">\n");
      out.write("\t\t\t\t\t\t\t<form action=\"loginCheck.do\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"id\">Your ID</label> <input type=\"text\" name=\"m_id\" id=\"m_id\" class=\"inpt\"\n");
      out.write("\t\t\t\t\t\t\t\t\trequired=\"required\" placeholder=\"Your ID\"> <label for=\"password\">Your\n");
      out.write("\t\t\t\t\t\t\t\t\tpassword</label> <input type=\"password\" name=\"m_pw\" id=\"m_pw\" class=\"inpt\" required=\"required\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Your password\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"submit-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Sign in\" class=\"submit\"> <input type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"signUp\" value=\"회원가입\" class=\"submit\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"FindPW.jsp\" class=\"more\">Forgot your password</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"FindId.jsp\" class=\"more\">or id?</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</article>\n");
      out.write("\t\t\t\t<div class=\"half bg\"></div>\n");
      out.write("\t\t\t</section>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\t$(\"#signUp\").click(function() {\n");
      out.write("\t\t\t\tdocument.location.href = \"SignUp.jsp\";\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
