/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-24 08:34:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SignIn2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link href=\"css/maincss.css\" rel=\"stylesheet\">\r\n");
      out.write("<style rel=\"stylesheet\">\r\n");
      out.write("@import url(https://fonts.googleapis.com/css?family=Lato:400,700);\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn {\r\n");
      out.write("\tfont-family: 'Lato', sans-serif;\r\n");
      out.write("\tbackground-color: #f8f8f8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\theight: 550px;\r\n");
      out.write("\tmargin: 80px auto 0;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\tbox-shadow: rgba(0, 0, 0, 0.1) 0px 10px 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .half {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tpadding: 58px 40px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container h1 {\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tmargin-bottom: 23px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-indent: 6px;\r\n");
      out.write("\tletter-spacing: 7px;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tcolor: #263238;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .tabs {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmargin-bottom: 29px;\r\n");
      out.write("\tborder-bottom: 1px solid #d9d9d9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .tabs .tab {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-bottom: -1px;\r\n");
      out.write("\tpadding: 20px 15px 10px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tletter-spacing: 0;\r\n");
      out.write("\tborder-bottom: 1px solid #d9d9d9;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("\ttransition: all 0.1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .tabs .tab a {\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tcolor: #d9d9d9;\r\n");
      out.write("\ttransition: all 0.1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .tabs .tab.active a, #signIn .container .tabs .tab:hover a\r\n");
      out.write("\t{\r\n");
      out.write("\tcolor: #263238;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .tabs .tab.active {\r\n");
      out.write("\tborder-bottom: 1px solid #263238;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content form {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\theight: 320px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content label {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #263238;\r\n");
      out.write("\t-moz-user-select: -moz-none;\r\n");
      out.write("\t-ms-user-select: none;\r\n");
      out.write("\t-webkit-user-select: none;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content input.inpt {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 42px;\r\n");
      out.write("\tmargin-bottom: 12px;\r\n");
      out.write("\tpadding: 16px 13px;\r\n");
      out.write("\tcolor: #999999;\r\n");
      out.write("\tborder: 1px solid #d9d9d9;\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("\t-moz-border-radius: 2px;\r\n");
      out.write("\t-webkit-border-radius: 2px;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content input.inpt::-webkit-input-placeholder\r\n");
      out.write("\t{\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor: #999999;\r\n");
      out.write("\tfont-family: 'Lato', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content input.inpt:focus {\r\n");
      out.write("\tborder-color: #999999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content input.submit {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 42px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 42px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tletter-spacing: 2px;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tcolor: #263238;\r\n");
      out.write("\tborder: 1px solid #263238;\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("\t-moz-border-radius: 2px;\r\n");
      out.write("\t-webkit-border-radius: 2px;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content input.submit:hover {\r\n");
      out.write("\tbackground-color: #263238;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\t-moz-transition: all 0.2s;\r\n");
      out.write("\t-o-transition: all 0.2s;\r\n");
      out.write("\t-webkit-transition: all 0.2s;\r\n");
      out.write("\ttransition: all 0.2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content input:focus {\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content .checkbox {\r\n");
      out.write("\tmargin-top: 4px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tclip: rect(0, 0, 0, 0);\r\n");
      out.write("\twidth: 0;\r\n");
      out.write("\theight: 0;\r\n");
      out.write("\tmargin: 17px -1px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content .checkbox+label {\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content .checkbox+label:before {\r\n");
      out.write("\tcontent: \"\\A\";\r\n");
      out.write("\tcolor: #999999;\r\n");
      out.write("\tfont-family: Verdana;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 8px;\r\n");
      out.write("\tline-height: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\t-moz-border-radius: 2px;\r\n");
      out.write("\t-webkit-border-radius: 2px;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("\tbackground: transparent;\r\n");
      out.write("\tborder: 1px solid #d9d9d9;\r\n");
      out.write("\twidth: 11px;\r\n");
      out.write("\theight: 11px;\r\n");
      out.write("\tmargin: -2px 8px 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content .submit-wrap {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content .submit-wrap a {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #999999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content .submit-wrap a:hover {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#signIn .mainWrap .container .content .signup-cont {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<body id=\"signIn\">\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t<div class=\"mainWrap\">\r\n");
      out.write("\t\t\t<section class=\"container\">\r\n");
      out.write("\t\t\t\t<article class=\"half\">\r\n");
      out.write("\t\t\t\t\t<h1>NONAME</h1>\r\n");
      out.write("\t\t\t\t\t<div class=\"tabs\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tab signin active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#signin\">Sign in</a>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"signin-cont cont\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"email\">Your email</label> <input type=\"email\" name=\"email\" id=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"inpt\" required=\"required\" placeholder=\"Your email\"> <label for=\"password\">Your\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpassword</label> <input type=\"password\" name=\"password\" id=\"password\" class=\"inpt\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trequired=\"required\" placeholder=\"Your password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"submit-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Sign in\" class=\"submit\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"signUp\" value=\"회원가입\" class=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"FindPW.jsp\" class=\"more\">Forgot your password</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"FindId.jsp\" class=\"more\">or id?</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t<div class=\"half bg\"></div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#signUp\").click(function() {\r\n");
      out.write("\t\t\t\tdocument.location.href = \"SignUp.jsp\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
